services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=insurance_core_db'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d insurance_core_db']
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - '8081:8081'
    environment:
      - 'DB_URL=jdbc:postgresql://postgres:5432/insurance_core_db'
      - 'DB_USERNAME=${DB_USERNAME}'
      - 'DB_PASSWORD=${DB_PASSWORD}'
      - 'SPRING_DOCKER_COMPOSE_ENABLED=false'
    depends_on:
      postgres:
        condition: service_healthy
